/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PhotosIndexImport } from './routes/photos/index'
import { Route as PhotosAlbumIdImport } from './routes/photos/$albumId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PhotosIndexRoute = PhotosIndexImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRoute,
} as any)

const PhotosAlbumIdRoute = PhotosAlbumIdImport.update({
  id: '/photos/$albumId',
  path: '/photos/$albumId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/photos/$albumId': {
      id: '/photos/$albumId'
      path: '/photos/$albumId'
      fullPath: '/photos/$albumId'
      preLoaderRoute: typeof PhotosAlbumIdImport
      parentRoute: typeof rootRoute
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/photos/$albumId': typeof PhotosAlbumIdRoute
  '/photos': typeof PhotosIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/photos/$albumId': typeof PhotosAlbumIdRoute
  '/photos': typeof PhotosIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/photos/$albumId': typeof PhotosAlbumIdRoute
  '/photos/': typeof PhotosIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/photos/$albumId' | '/photos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/photos/$albumId' | '/photos'
  id: '__root__' | '/' | '/photos/$albumId' | '/photos/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhotosAlbumIdRoute: typeof PhotosAlbumIdRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhotosAlbumIdRoute: PhotosAlbumIdRoute,
  PhotosIndexRoute: PhotosIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/photos/$albumId",
        "/photos/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/photos/$albumId": {
      "filePath": "photos/$albumId.tsx"
    },
    "/photos/": {
      "filePath": "photos/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
