/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as AlbumsIndexImport } from './routes/albums/index'
import { Route as UsersUserAccordionImport } from './routes/users/userAccordion'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const AlbumsIndexRoute = AlbumsIndexImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserAccordionRoute = UsersUserAccordionImport.update({
  id: '/users/userAccordion',
  path: '/users/userAccordion',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/users/userAccordion': {
      id: '/users/userAccordion'
      path: '/users/userAccordion'
      fullPath: '/users/userAccordion'
      preLoaderRoute: typeof UsersUserAccordionImport
      parentRoute: typeof rootRoute
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users/userAccordion': typeof UsersUserAccordionRoute
  '/albums': typeof AlbumsIndexRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users/userAccordion': typeof UsersUserAccordionRoute
  '/albums': typeof AlbumsIndexRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/users/userAccordion': typeof UsersUserAccordionRoute
  '/albums/': typeof AlbumsIndexRoute
  '/users/': typeof UsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users/userAccordion' | '/albums' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users/userAccordion' | '/albums' | '/users'
  id: '__root__' | '/' | '/users/userAccordion' | '/albums/' | '/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersUserAccordionRoute: typeof UsersUserAccordionRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersUserAccordionRoute: UsersUserAccordionRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/users/userAccordion",
        "/albums/",
        "/users/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/users/userAccordion": {
      "filePath": "users/userAccordion.tsx"
    },
    "/albums/": {
      "filePath": "albums/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
